services:
  jsonviz:
    image: jsonviz
    container_name: jsonviz
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - NODE_ENV=production